constants:
  file:
    directory: D:\student\backend\upload


spring:
  datasource:
    url: jdbc:mariadb://localhost/book
    username: root
    password: green502


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

google:
  books:
    api-key: AIzaSyDJEtarXIO2-Fmsiu6kWGvj7ZNBCqNk6Ew
    base-url: https://www.googleapis.com/books/v1